### ISSUE TITLE
Validate unique version names in versionInfo

### ISSUE THREAD

**Issue by sriumcp** [iter8-tools/etc3#130] opened 2021-03-02 19:04 UTC
**Is your feature request related to a problem? Please describe.**
Names of versions are used to uniquely identify the versions. 

**Describe the solution you'd like**
Uniqueness of version names need to be verified as part of validation.

**Comment by kalantar** [comment] 2021-03-03 18:47
This is a duplicate of issue https://github.com/iter8-tools/etc3/issues/104

**Closed by kalantar** 2021-03-03 18:47 UTC
